import { spawnSync } from 'node:child_process';
import { existsSync, readFileSync, readdirSync } from 'node:fs';
import { join } from 'node:path';
import { isOpen } from '../ledger-core.ts';
import type { LedgerItem, LedgerRow } from '../ledger-core.ts';
import type { Args } from './args.ts';
import type { BoardContext } from './board.ts';
import { cell, clip, itemText, slug } from './format.ts';

/** A ticket row as the derived index returns it. */
export interface TicketRow { id: string; status?: string; title?: string }
/** What the retro and archive checks read from the run. */
export interface RetroContext {
    vault: string;
    project: string;
    ticketsBase: () => string;
    retroDir: () => string;
    readLedger: () => LedgerRow[];
    fold: BoardContext['fold'];
    mapStream: (stream: string | undefined) => string | undefined;
    today: () => string;
    arg: Args['arg'];
    ticketStatuses: (ids: string[]) => Map<string, TicketRow> | null;
}

export const PR_WORDS = /\bPRs?\b|pull request|release|#\d{2,}/i;
export const LEARNING = /learned|lesson|ruled out|cause/i;
export const TICKET_ID = /\b(?:[A-Za-z][A-Za-z0-9]*-)+\d{1,5}\b/g;

/** Ticket status through ledger-index.ts (the derived index); null when the index cannot be read. */
export function ticketStatuses(ctx: Pick<RetroContext, 'vault' | 'project' | 'ticketsBase'>, ids: string[]): Map<string, TicketRow> | null {
    const { vault, project, ticketsBase } = ctx;
    const safe = ids.filter((id) => /^[\w.-]+$/.test(id));
    if (!safe.length) return new Map();
    const sql = `select id, status, title from tickets where id in (${safe.map((id) => `'${id}'`).join(',')})`;
    const r = spawnSync(process.execPath, [
        new URL('../../ledger-index.ts', import.meta.url).pathname, 'query', '--sql', sql, '--json',
        '--vault', vault, '--project', project, '--tickets-vault', ticketsBase(),
    ], { encoding: 'utf8' });
    if (r.status !== 0) return null;
    try { const rows: TicketRow[] = JSON.parse(r.stdout); return new Map(rows.map((t): [string, TicketRow] => [t.id, t])); } catch { return null; }
}

export function retroText(ctx: RetroContext, stream: string): string {
    const { readLedger, fold, mapStream, today, ticketStatuses: statusesOf } = ctx;
    const entries = readLedger();
    const items = fold(entries).items.filter((i) => i.stream === stream);
    const facts = entries.filter((e) => e.kind === 'fact' && mapStream(e.stream) === stream);
    const carriedOut = entries.filter((e) => e.kind === 'carry' && typeof e.from === 'string' && mapStream(e.from) === stream && mapStream(e.stream) !== stream);
    const open = items.filter(isOpen);
    const done = items.filter((i) => i.state === 'done');
    const dropped = items.filter((i) => i.state === 'dropped');

    const touched = [
        ...items.flatMap((i) => [{ id: i.id, ts: i.ts, date: i.date, text: i.text, kind: i.kind }, ...(i.closedBy ? [{ id: i.closedBy.id, ts: i.closedBy.ts, date: i.closedBy.date, text: i.closedBy.text, kind: i.closedBy.kind }] : [])]),
        ...facts.map((f) => ({ id: f.id, ts: f.ts, date: f.date, text: f.text, kind: 'fact' })),
    ].sort((a, b) => String(a.ts).localeCompare(String(b.ts)));
    const first = touched[0];
    const last = touched[touched.length - 1];
    const perDay = new Map<string | undefined, number>();
    for (const t of touched) perDay.set(t.date, (perDay.get(t.date) || 0) + 1);

    const shipped = done.filter((i) => PR_WORDS.test(itemText(i)) || (i.refs || []).length);
    const refsOf = (i: LedgerItem): string[] => [...new Set([...(itemText(i).match(/#\d{2,}/g) || []), ...(i.refs || []).filter((r) => /^#\d+$/.test(r))])];
    const learnings = items.filter((i) => LEARNING.test(itemText(i)));

    const cited = new Map<string, boolean>();
    for (const i of items) {
        if (i.ticket) cited.set(i.ticket, true);
        for (const id of itemText(i).match(TICKET_ID) || []) if (!cited.has(id)) cited.set(id, false);
    }
    const statuses = statusesOf([...cited.keys()]);

    const out = [
        '---', 'status: draft', `stream: ${stream}`, `generated: ${today()}`, 'type: retro', '---', '',
        `# ${stream} retro`, '',
        '> Draft generated by `journal.mjs retro`. Polish it, then change `status:` above to `reviewed` and fill every "Promoted to" line before `archive`.', '',
        '## Summary', '',
        `- Items done: ${done.length}`, `- Items dropped: ${dropped.length}`, `- Items open: ${open.length}`,
        `- Other rows (notes, resolved, decisions): ${items.length - done.length - dropped.length - open.length}`,
        `- Facts recorded: ${facts.length}`,
        `- Date span: ${first ? `${first.date} to ${last.date}` : '(no rows)'}`, '',
        '## Timeline', '',
        first ? `- First row: ${first.date} \`${first.id}\` ${clip(first.text, 100)}` : '- (no rows)',
        last ? `- Last row: ${last.date} \`${last.id}\` ${clip(last.text, 100)}` : '',
        '', '| Date | Rows |', '|---|---|',
        ...[...perDay].sort((a, b) => (a[0] ?? '').localeCompare(b[0] ?? '')).map(([d, n]) => `| ${d} | ${n} |`), '',
        '## Facts', '',
        ...(facts.length ? ['| Key | Value | Date |', '|---|---|---|', ...facts.map((f) => `| ${cell(f.key)} | ${cell(f.value)} | ${f.date} |`)] : ['_none_']), '',
        '## Shipped', '',
        ...(shipped.length ? shipped.map((i) => `- \`${i.id}\` ${clip(itemText(i), 200)}${refsOf(i).length ? ` (${refsOf(i).join(', ')})` : ''}`) : ['_none_']), '',
        '## Tickets referenced', '',
        ...(cited.size ? [
            '| Ticket | Status | Title |', '|---|---|---|',
            ...[...cited].flatMap(([id, explicit]) => {
                const t = statuses?.get(id);
                if (t) return [`| ${cell(id)} | ${cell(t.status)} | ${cell(t.title)} |`];
                return explicit || !statuses ? [`| ${cell(id)} | ${statuses ? 'not in index' : 'index unavailable'} | |`] : [];
            }),
        ] : ['_none_']), '',
        '## Learnings', '',
        ...(learnings.length ? learnings.map((i) => `- \`${i.id}\` ${clip(itemText(i), 300)}`) : ['_none_']), '',
        '## Open follow-ups', '',
        ...(open.length ? open.map((i) => `- \`${i.id}\` [${i.kind}] ${clip(i.text, 200)}`) : ['_none_']),
        ...carriedOut.map((c) => `- carried to ${mapStream(c.stream)}: \`${c.carries}\``), '',
        '## Promoted to', '',
        'One line per learning. Give each a target (a DECISIONS.md entry, a skill, a ticket id) or `one-off`.', '',
        ...(learnings.length ? learnings.map((i) => `- [ ] ${clip(itemText(i), 120)} (\`${i.id}\`) — Promoted to: `) : ['_no learnings to promote_']), '',
    ];
    return out.join('\n');
}

export function findRetro(ctx: Pick<RetroContext, 'arg' | 'retroDir'>, stream: string): string | null {
    const { arg, retroDir } = ctx;
    const explicit = arg('retro');
    if (explicit) return existsSync(explicit) ? explicit : null;
    const dirPath = retroDir();
    if (!existsSync(dirPath)) return null;
    const hits = readdirSync(dirPath).filter((n) => n.startsWith(`${slug(stream)}-retro-`) && n.endsWith('.md')).sort();
    return hits.length ? join(dirPath, hits[hits.length - 1]) : null;
}

export const retroStatus = (text: string): string => (text.match(/^---\n([\s\S]*?)\n---/)?.[1].match(/^status:\s*["']?([^"'\s]+)/m) || [])[1] || 'draft';

/** Lines of the "Promoted to" checklist that still have no target. */
export function unfilledPromotions(text: string): string[] {
    const sec = text.split(/^## Promoted to\s*$/m)[1];
    if (!sec) return [];
    return sec.split(/^## /m)[0].split('\n').filter((l) => /^- \[[ xX]\] /.test(l))
        .filter((l) => !((l.match(/Promoted to:\s*(.*)$/) || [])[1] || '').trim());
}

export function archiveBlockers(ctx: Pick<RetroContext, 'arg' | 'retroDir'>, stream: string, items: LedgerItem[]): { blockers: string[]; retro: string | null } {
    const { retroDir } = ctx;
    const blockers: string[] = [];
    const open = items.filter((i) => i.stream === stream && isOpen(i));
    for (const i of open) blockers.push(`open item ${i.id} [${i.kind}]: ${clip(i.text, 80)} (finish it, or \`carry ${i.id} --to <stream>\`)`);
    const retro = findRetro(ctx, stream);
    if (!retro) blockers.push(`no retro doc found in ${retroDir()} (run \`retro ${stream}\`)`);
    else {
        const text = readFileSync(retro, 'utf8');
        if (retroStatus(text) === 'draft') blockers.push(`retro ${retro} still has status: draft`);
        const blank = unfilledPromotions(text);
        if (blank.length) blockers.push(`${blank.length} "Promoted to" line(s) in ${retro} have no target or one-off`);
    }
    return { blockers, retro };
}
