// Run: node --test scripts/library-index.test.ts
import { test, beforeEach } from 'node:test';
import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { mkdtempSync, mkdirSync, writeFileSync, readFileSync, symlinkSync, statSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { mergeIndex, renderBlock, START, END } from './lib/library/index-page.ts';
import type { LibraryPage } from './lib/library/pages.ts';

process.env.MAESTRO_LOCAL_CONFIG = '';
const SCRIPT = new URL('./library-index.ts', import.meta.url).pathname;
let vault: string;

const run = (...args: string[]) => {
    const r = spawnSync(process.execPath, [SCRIPT, '--vault', vault, ...args], { encoding: 'utf8', env: { ...process.env, VAULT_ROOT: '' } });
    return { code: r.status, out: r.stdout, err: r.stderr };
};
const put = (rel: string, text: string): void => { mkdirSync(dirname(join(vault, rel)), { recursive: true }); writeFileSync(join(vault, rel), text); };
const read = (rel: string): string => readFileSync(join(vault, rel), 'utf8');
const pageText = (kind: string, status: string, title: string, readWhen: string): string => `---
type: library
kind: ${kind}
repo: alpha
stream: S
components: [core]
status: ${status}
verified-at: 2026-10-02
verify-how: "x"
composed-by: composer
---

# ${title}

Read when: ${readWhen}

## Facts

- f (verified 2026-10-02, a.md:1)
`;
const INDEX = '---\ntype: library-index\nrepo: alpha\ncomponents: [core]\n---\n\n# alpha library index\n\nHand-written intro stays.\n';

beforeEach(() => {
    vault = mkdtempSync(join(tmpdir(), 'lindex-'));
    put('Projects/alpha/Knowledge/zeta.md', pageText('gotcha', 'stale', 'Zeta', 'you touch zeta'));
    put('Projects/alpha/Knowledge/alpha-flow.md', pageText('how-it-works', 'current', 'Flow', 'you trace the flow'));
    put('Projects/alpha/Runbooks/restart.md', pageText('runbook', 'current', 'Restart', 'it hangs'));
    put('Projects/alpha/INDEX.md', INDEX);
});

test('appends a sorted Pages block once, keeping the frontmatter and the hand-written text', () => {
    const r = run();
    assert.equal(r.code, 0, r.err);
    assert.match(r.out, /^alpha: 3 pages, appended a ## Pages block/);
    const text = read('Projects/alpha/INDEX.md');
    assert.ok(text.startsWith(INDEX.trimEnd()));
    const lines = text.split('\n').filter((l) => l.startsWith('- [['));
    // Sorted by vault path, so Knowledge pages come before Runbooks.
    assert.deepEqual(lines, [
        '- [[alpha-flow]]: how-it-works, you trace the flow (verified 2026-10-02)',
        '- [[zeta]]: gotcha, you touch zeta (verified 2026-10-02 STALE)',
        '- [[restart]]: runbook, it hangs (verified 2026-10-02)',
    ]);
    assert.match(text, /Generated by library-index\.ts from 3 library pages/);
});

test('a rerun writes nothing and a page change updates only the block', () => {
    run();
    const first = read('Projects/alpha/INDEX.md');
    const mtime = statSync(join(vault, 'Projects/alpha/INDEX.md')).mtimeMs;
    const again = run();
    assert.match(again.out, /3 pages, unchanged/);
    assert.equal(statSync(join(vault, 'Projects/alpha/INDEX.md')).mtimeMs, mtime);
    put('Projects/alpha/Knowledge/zeta.md', pageText('gotcha', 'current', 'Zeta', 'you touch zeta now'));
    assert.match(run().out, /3 pages, updated/);
    const text = read('Projects/alpha/INDEX.md');
    assert.match(text, /\[\[zeta\]\]: gotcha, you touch zeta now \(verified 2026-10-02\)/);
    assert.equal(text.split(START)[0], first.split(START)[0]);
});

test('--check exits 1 and writes nothing while an index is out of date, then 0', () => {
    const r = run('--check');
    assert.equal(r.code, 1);
    assert.match(r.out, /would append/);
    assert.equal(read('Projects/alpha/INDEX.md'), INDEX);
    assert.equal(run('--dry-run').code, 0);
    run();
    assert.equal(run('--check').code, 0);
});

test('a project with pages and no INDEX.md is named and skipped, never created', () => {
    put('Projects/beta/Knowledge/b.md', pageText('how-to', 'current', 'B', 'always').replace('repo: alpha', 'repo: beta'));
    const r = run();
    assert.match(r.out, /^beta: 1 page, skipped: no INDEX.md/m);
    assert.throws(() => read('Projects/beta/INDEX.md'));
});

test('a symlinked INDEX.md is not written through', () => {
    put('outside.md', 'untouched\n');
    spawnSync('rm', [join(vault, 'Projects/alpha/INDEX.md')]);
    symlinkSync(join(vault, 'outside.md'), join(vault, 'Projects/alpha/INDEX.md'));
    assert.match(run().out, /skipped: no INDEX.md/);
    assert.equal(read('outside.md'), 'untouched\n');
});

test('usage and read errors exit 2, never a silent pass', () => {
    assert.equal(run('--repo').code, 2);
    assert.equal(run('--bogus').code, 2);
    assert.equal(run('--repo', 'nope').code, 2);
    assert.equal(run('--repo', '../x').code, 2);
    const empty = spawnSync(process.execPath, [SCRIPT, '--vault', join(vault, 'nowhere')], { encoding: 'utf8' });
    assert.equal(empty.status, 2);
});

test('renderBlock links by vault path when two pages share a name, and mergeIndex keeps text after the end marker', () => {
    const mk = (path: string): LibraryPage => ({ path, repo: 'alpha', kind: 'how-to', title: 't', readWhen: '', components: [], stream: '', status: 'superseded', verifiedAt: '', body: '', links: [] });
    const block = renderBlock([mk('Projects/alpha/Knowledge/x.md'), mk('Projects/alpha/Runbooks/x.md')]);
    assert.match(block, /\[\[Projects\/alpha\/Knowledge\/x\]\]: how-to, no Read when line \(verified never SUPERSEDED\)/);
    const merged = mergeIndex(`top\n${START}\nold\n${END}\ntail\n`, block);
    assert.equal(merged.state, 'replaced');
    assert.ok(merged.text.startsWith('top\n') && merged.text.endsWith(`${END}\ntail\n`) && !merged.text.includes('old'));
});

// Shapes are assembled at run time so this file holds no literal token.
const TOKEN = ['gh', 'p_abcdefghijklmnopqrstuvwxyz0123456789'].join('');
const SECRET_READ_WHEN = ['you set password=hunter2hunter2 first', `you export ${TOKEN} now`, 'you open postgres://svc:s3cretpass@db.example.test/x'];
const PHI_READ_WHEN = ['the patient SSN is 123-45-6789', 'call 555-123-4567 or mail test@example.com'];

test('a read-when line with a secret or PHI shape is withheld from INDEX.md', () => {
    [...SECRET_READ_WHEN, ...PHI_READ_WHEN].forEach((rw, i) => put(`Projects/alpha/Knowledge/leak-${i}.md`, pageText('gotcha', 'current', `Leak ${i}`, rw)));
    run();
    const text = read('Projects/alpha/INDEX.md');
    for (const frag of ['hunter2', 'ghp_', 's3cretpass', '123-45-6789', '555-123-4567', 'test@example.com']) assert.ok(!text.includes(frag), frag);
    assert.equal(text.split('(withheld: fails the secret scan, run library-check)').length - 1, 5);
    assert.match(text, /\[\[restart\]\]: runbook, it hangs/);
});

test('a read-when line or file name holding a block marker does not make INDEX.md grow on each run', () => {
    put('Projects/alpha/Knowledge/tool.md', pageText('tool', 'current', 'Tool', `edit the block between ${START} and ${END} by hand`));
    put('Projects/alpha/Knowledge/odd-->name.md', pageText('tool', 'current', 'Odd', 'a file whose name holds a comment end'));
    run();
    const lengths = [1, 2, 3].map(() => { run(); return read('Projects/alpha/INDEX.md').split('\n').length; });
    assert.deepEqual(new Set(lengths).size, 1);
    const text = read('Projects/alpha/INDEX.md');
    assert.equal(text.split(START).length, 2);
    assert.equal(text.split(END).length, 2);
    assert.equal(run('--check').code, 0);
});

test('a project whose last page is deleted gets an empty block, and --check notices first', () => {
    put('Projects/beta/Knowledge/b.md', pageText('how-to', 'current', 'B', 'always').replace('repo: alpha', 'repo: beta'));
    put('Projects/beta/INDEX.md', INDEX.replace('alpha', 'beta'));
    run();
    assert.match(read('Projects/beta/INDEX.md'), /\[\[b\]\]/);
    spawnSync('rm', [join(vault, 'Projects/beta/Knowledge/b.md')]);
    assert.equal(run('--check').code, 1);
    const r = run();
    assert.match(r.out, /^beta: 0 pages, updated/m);
    const text = read('Projects/beta/INDEX.md');
    assert.ok(!text.includes('[[b]]'));
    assert.match(text, /from 0 library pages/);
    assert.equal(run('--check').code, 0);
});

test('an INDEX.md that was never generated is left alone when its project has no pages', () => {
    put('Projects/gamma/INDEX.md', INDEX.replace('alpha', 'gamma'));
    run();
    assert.equal(read('Projects/gamma/INDEX.md'), INDEX.replace('alpha', 'gamma'));
});

test('page order is by code point, whatever the locale of the machine', () => {
    put('Projects/alpha/Knowledge/ä-page.md', pageText('tool', 'current', 'Umlaut', 'you read it'));
    put('Projects/alpha/Knowledge/zz-page.md', pageText('tool', 'current', 'Zz', 'you read it too'));
    const names = (locale: string): string[] => {
        const r = spawnSync(process.execPath, [SCRIPT, '--vault', vault, '--dry-run'], { encoding: 'utf8', env: { ...process.env, VAULT_ROOT: '', LC_ALL: locale, LANG: locale } });
        assert.equal(r.status, 0, r.stderr);
        run();
        return read('Projects/alpha/INDEX.md').split('\n').filter((l) => l.startsWith('- [[')).map((l) => l.slice(4, l.indexOf(']]')));
    };
    const order = names('C');
    assert.ok(order.indexOf('zz-page') < order.indexOf('ä-page'));
    assert.equal(run('--check').code, 0);
});

const MALFORMED: [string, string][] = [
    ['a lone start marker with human lines after it', `${INDEX}\n${START}\nkeep me one\nkeep me two\n`],
    ['an end marker before the start marker', `${INDEX}\n${END}\nkeep me\n${START}\n`],
    ['prose that names both markers on one line', `${INDEX}\nThe block between ${START} and ${END} is generated.\n`],
    ['two start markers', `${INDEX}\n${START}\nold\n${END}\n${START}\n`],
    ['a start line plus the marker quoted in prose', `${INDEX}\nWrite ${END} to close.\n${START}\nold\n${END}\n`],
];

for (const [name, content] of MALFORMED) {
    test(`INDEX.md with ${name} is left byte-identical, named, and reported by library-check`, () => {
        put('Projects/alpha/INDEX.md', content);
        for (let i = 0; i < 3; i += 1) {
            const r = run();
            assert.equal(r.code, 1, r.out);
            assert.match(r.out, /^alpha: 3 pages, NOT rewritten/m);
            assert.equal(read('Projects/alpha/INDEX.md'), content);
        }
        assert.equal(run('--check').code, 1);
        const check = spawnSync(process.execPath, [new URL('./library-check.ts', import.meta.url).pathname, '--vault', vault], { encoding: 'utf8' });
        assert.match(check.stdout, /Projects\/alpha\/INDEX\.md {2}index-markers/);
        assert.equal(check.status, 1);
    });
}

test('a page-less project whose INDEX.md has a lone marker is reported and left alone', () => {
    const content = `${INDEX.replace('alpha', 'delta')}\n${START}\nkeep me\n`;
    put('Projects/delta/INDEX.md', content);
    const r = run();
    assert.match(r.out, /^delta: 0 pages, NOT rewritten/m);
    assert.equal(read('Projects/delta/INDEX.md'), content);
});

test('a well-formed pair with indentation around the markers is still replaced in place', () => {
    put('Projects/alpha/INDEX.md', `${INDEX}\n  ${START}  \nold\n${END}\ntail line\n`);
    assert.match(run().out, /3 pages, updated/);
    const text = read('Projects/alpha/INDEX.md');
    assert.ok(text.endsWith(`${END}\ntail line\n`) && text.includes('Hand-written intro stays.') && !text.includes('\nold\n'));
    assert.equal(run('--check').code, 0);
});

test('read-when text built to rebuild a marker or hide a token does not grow INDEX.md or reach it', () => {
    const token = ['gh', 'p_'].join('') + 'abcdefghijklmnopqrstuvwxyz0123456789';
    put('Projects/alpha/Knowledge/sneaky-1.md', pageText('tool', 'current', 'S1', `orchard <!<!---->-- library-index:end --<!---->> tail`));
    put('Projects/alpha/Knowledge/sneaky-2.md', pageText('tool', 'current', 'S2', token.replace('_', '_<!---->')));
    put('Projects/alpha/Knowledge/sneaky-3.md', pageText('tool', 'current', 'S3', token.replace('_', '_​')));
    run();
    const lengths = [1, 2, 3].map(() => { run(); return read('Projects/alpha/INDEX.md').split('\n').length; });
    assert.equal(new Set(lengths).size, 1);
    const text = read('Projects/alpha/INDEX.md');
    assert.equal(text.split(END).length, 2);
    assert.ok(!text.includes('abcdefghijklmnopqrstuvwxyz0123456789'));
    assert.equal(run('--check').code, 0);
});

test('a verified-at value with a PHI shape is withheld whole, not cut to ten characters first', () => {
    put('Projects/alpha/Knowledge/odd-date.md', pageText('tool', 'current', 'Odd', 'you read it').replace('verified-at: 2026-10-02', 'verified-at: 123-45-6789@abc1234'));
    run();
    const text = read('Projects/alpha/INDEX.md');
    assert.ok(!text.includes('123-45-678'));
    assert.match(text, /\[\[odd-date\]\]: tool, you read it \(verified \(withheld/);
});
