/**
 * PR BODY: the pure checks pr-open.ts runs on a PR body before it opens anything (reference/git.md, "PR body").
 * No I/O here, so every rule is unit-testable on a string.
 */
import {
  PR_BODY_SECTIONS, PR_BODY_CHECK_PRIVATE, PR_BODY_PRIVATE_WORDS, PR_BODY_PRIVATE_PATTERNS, PR_BODY_CHECK_VOICE, PR_BODY_VOICE_NAMES, PR_BODY_CHECK_RISK, PR_BODY_CHECK_VERIFY, PR_BODY_CHECK_FORBIDDEN, PR_BODY_CHECK_DIAGRAM, PR_DIAGRAM_MIN_FILES,
} from './local-config.ts';

/** Which rules run. Each switch maps to a local-config key (`pr_body_*`); the defaults are the configured values. */
export interface BodyRules { sections: string[]; risk: boolean; verify: boolean; forbidden: boolean; diagram: boolean; diagramMinFiles: number;
  private: boolean; privateWords: string[]; privatePatterns: string[]; voice: boolean; voiceNames: string[] }
/** What the diff says about the PR, for the rules that need it. */
export interface BodyContext { stacked: boolean; codeFiles: number; title?: string }

export const DEFAULT_RULES: BodyRules = {
  sections: PR_BODY_SECTIONS, risk: PR_BODY_CHECK_RISK, verify: PR_BODY_CHECK_VERIFY, forbidden: PR_BODY_CHECK_FORBIDDEN,
  diagram: PR_BODY_CHECK_DIAGRAM, diagramMinFiles: PR_DIAGRAM_MIN_FILES,
  private: PR_BODY_CHECK_PRIVATE, privateWords: PR_BODY_PRIVATE_WORDS, privatePatterns: PR_BODY_PRIVATE_PATTERNS, voice: PR_BODY_CHECK_VOICE, voiceNames: PR_BODY_VOICE_NAMES,
};

const PLACEHOLDER = /^(?:[-*_\s.]*(?:tbd|todo|n\/a|none|fill (?:me )?in|wip)[-*_\s.]*|[-*_\s.]*)$/i;
/** A line that is only a template slot such as `<why this change exists>`, which has not been filled in. */
const SLOT = /^[-*>\s]*(?:\d+\.\s*)?<[^<>\n]*>[-*\s.]*$/;
const FENCE_LINE = /^\s*(?:`{3,}|~{3,})/;

/** Patterns a PR body must not carry. Best effort: a pass is not a guarantee. The match is never printed, only the name. */
const FORBIDDEN: [string, RegExp][] = [
  ['an AI attribution line', /co-authored-by:|generated with \[?claude|assisted by (?:claude|copilot|an? ai)|\u{1F916}\s*generated/iu],
  ['a private key block', /-----BEGIN [A-Z ]*PRIVATE KEY-----/],
  ['an AWS access key id', /\b(?:AKIA|ASIA)[0-9A-Z]{16}\b/],
  ['a GitHub token', /\bgh[pousr]_[A-Za-z0-9]{30,}\b/],
  ['a credential assignment', /\b(?:api[_-]?key|secret|passw(?:or)?d|token)\s*[:=]\s*['"]?[A-Za-z0-9/+_-]{16,}/i],
  ['an SSN-shaped number', /\b\d{3}-\d{2}-\d{4}\b/],
  ['a medical record number', /\bMRN\s*[:#]?\s*\d{4,}/i],
];

/** References to a private workspace that a reader of the PR cannot resolve. Install-specific id formats come from `pr_body_private_patterns`. */
const PRIVATE: [string, RegExp][] = [
  ['a [[wiki-link]]', /\[\[[^\]\n]+\]\]/],
  ['an obsidian:// link', /obsidian:\/\//i],
];

/** Words that make a body read as written by someone else. The author's own names come from `pr_body_voice_names`. */
const NOT_FIRST_PERSON = /\b(?:ai[- ]generated|generated by (?:an? )?(?:ai|assistant|agent)|as an? (?:ai )?(?:assistant|agent)|(?:the|this|an?) (?:ai )?(?:assistant|agent) (?:wrote|made|changed|decided|did|ran|opened|added|fixed|chose))\b/i;

const clip = (line: string): string => (line.trim().length > 80 ? `${line.trim().slice(0, 77)}...` : line.trim());

/** Lines (outside code fences, for voice) that match one of the patterns, as "<where> line: <text>". */
function lineProblems(text: string, where: string, rules: BodyRules): string[] {
  const out: string[] = [];
  const custom = rules.privatePatterns.map((r): [string, RegExp] => [`a private id (${r})`, new RegExp(r, 'i')]);
  const names = rules.voiceNames.map((n) => new RegExp(`\\b${n.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\\b`, 'i'));
  const words = rules.privateWords.length ? new RegExp(`\\b(?:${rules.privateWords.map((w) => w.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')).join('|')})\\b`, 'i') : null;
  let fence = false;
  for (const line of text.split('\n')) {
    if (FENCE_LINE.test(line)) { fence = !fence; continue; }
    if (rules.private) {
      const hit = [...PRIVATE, ...custom].find(([, re]) => re.test(line));
      if (hit) out.push(`${where} has ${hit[0]}, which a reader cannot resolve (line: ${clip(line)})`);
      else if (words && !fence && words.test(line.replace(/`[^`]*`/g, ''))) out.push(`${where} has a private-workspace word (${rules.privateWords.join(', ')}), which a reader cannot resolve (line: ${clip(line)})`);
    }
    if (rules.voice && !fence) {
      const plain = line.replace(/`[^`]*`/g, '');
      if (NOT_FIRST_PERSON.test(plain) || names.some((re) => re.test(plain))) out.push(`${where} is not in the author's own voice (line: ${clip(line)})`);
    }
  }
  return out;
}

/** The text under each `##` title, to the next `#` or `##` heading; headings in fenced code or HTML comments are ignored. Fence lines stay in the text. */
function sectionsOf(body: string): Map<string, string> {
  const out = new Map<string, string>();
  let current = '';
  let fence = '';
  for (const line of body.replace(/<!--[\s\S]*?-->/g, '').split('\n')) {
    const mark = /^\s*(`{3,}|~{3,})/.exec(line)?.[1];
    if (mark && !fence) fence = mark[0];
    else if (mark && mark[0] === fence) fence = '';
    const heading = fence || mark ? null : /^(#{1,2})\s+(.+?)\s*$/.exec(line);
    if (heading) {
      current = heading[1] === '##' ? heading[2].toLowerCase() : '';
      if (current) out.set(current, out.get(current) ?? '');
    } else if (current) out.set(current, `${out.get(current)}${line}\n`);
  }
  return out;
}

const hasContent = (text: string): boolean => text.split('\n').some((l) => !FENCE_LINE.test(l) && !PLACEHOLDER.test(l.trim()) && !SLOT.test(l));

/** True when the section is `n/a` followed by a reason, the way a template slot is skipped on purpose. */
const naWithReason = (text: string): boolean => /^\s*n\/a\b[\s,:;.-]*\S/i.test(text.trim());

/** True when the text holds a fenced block with at least one non-blank line inside. */
function hasFilledFence(text: string): boolean {
  let open = '';
  let filled = false;
  for (const line of text.split('\n')) {
    const mark = FENCE_LINE.exec(line)?.[0].trim();
    if (mark && !open) { open = mark[0]; filled = false; }
    else if (mark && open && mark[0] === open) { if (filled) return true; open = ''; }
    else if (open && line.trim() && !SLOT.test(line)) filled = true;
  }
  return false;
}

const sectionMatching = (sections: Map<string, string>, re: RegExp): string | undefined => [...sections].find(([k]) => re.test(k))?.[1];

function riskProblems(sections: Map<string, string>): string[] {
  const text = sectionMatching(sections, /^risk/);
  if (text === undefined) return [];
  const level = /^[\s>*_-]*\**risk\**\s*:\s*\**\s*(low|medium|high)\b(?!\s*\|)/im.exec(text)?.[1].toLowerCase();
  if (!level) return ['the risk section has no "Risk: low | medium | high" line'];
  if (level !== 'high') return [];
  const rollback = sectionMatching(sections, /^rollback/);
  return rollback !== undefined && hasContent(rollback) && !naWithReason(rollback) ? [] : ['Risk is high, so the rollback section must say how to undo it (not empty, not n/a)'];
}

function verifyProblems(sections: Map<string, string>): string[] {
  const text = sectionMatching(sections, /^how to verify/);
  if (text === undefined || naWithReason(text) || hasFilledFence(text)) return [];
  return ['the verify section has no fenced code block with a command (or "n/a, <reason>")'];
}

const forbiddenProblems = (body: string): string[] => FORBIDDEN.filter(([, re]) => re.test(body)).map(([what]) => `the body contains ${what}`);

function diagramProblems(raw: string, ctx: BodyContext, min: number): string[] {
  const body = raw.replace(/<!--[\s\S]*?-->/g, '');
  if (!ctx.stacked && ctx.codeFiles <= min) return [];
  if (/^\s*(`{3,}|~{3,})\s*mermaid\b/im.test(body) || /^\s*[-*]?\s*\**diagram\**\s*:\s*\**\s*n\/a\b[\s,:;.-]*\S/im.test(body)) return [];
  return [`a ${ctx.stacked ? 'stacked PR' : `PR over ${min} code files`} needs a mermaid diagram or a "Diagram: n/a, <reason>" line`];
}

/** Problems that keep a PR body from opening: required sections with real content, then the structural rules. */
export function bodyProblems(body: string, rules: BodyRules = DEFAULT_RULES, ctx: BodyContext = { stacked: false, codeFiles: 0 }): string[] {
  const sections = sectionsOf(body);
  const missing = rules.sections.flatMap((name) => {
    const text = sections.get(name.toLowerCase());
    if (text === undefined) return [`missing a "## ${name}" section`];
    return hasContent(text) ? [] : [`"## ${name}" has no content (empty or a placeholder)`];
  });
  return [
    ...missing,
    ...(rules.risk ? riskProblems(sections) : []),
    ...(rules.verify ? verifyProblems(sections) : []),
    ...(rules.diagram ? diagramProblems(body, ctx, rules.diagramMinFiles) : []),
    ...(rules.forbidden ? forbiddenProblems(body) : []),
    ...lineProblems(body, 'the body', rules),
    ...(ctx.title ? lineProblems(ctx.title, 'the title', rules) : []),
  ];
}
